In [1]:
import pandas as pd

# 전국도시철도역사정보표준데이터 preprocessing

In [25]:
sub = pd.read_csv('C:/Users/1102j/anaconda/dataScience/project/지하철/전국도시철도역사정보표준데이터.csv', encoding='utf-8')
sub.head()

,역번호,역사명,노선번호,노선명,영문역사명,한자역사명,환승역구분,환승노선번호,환승노선명,역위도,역경도,운영기관명,역사도로명주소,역사전화번호,데이터기준일자,제공기관코드,제공기관명
0,2545,군자,S1105,서울 도시철도 5호선,Gunja,君子,환승역,S1107,서울 도시철도 7호선,37.557134,127.079433,서울교통공사,서울특별시 광진구 천호대로 지하550,02-6311-5441,2021-04-09,B553766,서울교통공사
1,2546,아차산,S1105,서울 도시철도 5호선,Achasan,峨嵯山,일반역,NaN,NaN,37.552036,127.089601,서울교통공사,서울특별시 광진구 천호대로 지하657,02-6311-5451,2021-04-09,B553766,서울교통공사
2,2547,광나루,S1105,서울 도시철도 5호선,Gwangnaru,廣渡口,일반역,NaN,NaN,37.545048,127.103512,서울교통공사,서울특별시 광진구 아차산로 지하571 (광장동),02-6311-5461,2021-04-09,B553766,서울교통공사
3,2548,천호,S1105,서울 도시철도 5호선,Cheonho,千戶,일반역,NaN,NaN,37.538424,127.123623,서울교통공사,서울특별시 강동구 천호대로 지하997 (천호동),02-6311-5471,2021-04-09,B553766,서울교통공사
4,2549,강동,S1105,서울 도시철도 5호선,Gangdong,江東,일반역,NaN,NaN,37.535879,127.132079,서울교통공사,서울특별시 강동구 천호대로 지하1097 (천호동),02-6311-5481,2021-04-09,B553766,서울교통공사

In [26]:
sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1015 entries, 0 to 1014
Data columns (total 17 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   역번호      1015 non-null   object
 1   역사명      1015 non-null   object
 2   노선번호     1015 non-null   object
 3   노선명      1015 non-null   object
 4   영문역사명    1015 non-null   object
 5   한자역사명    1003 non-null   object
 6   환승역구분    1015 non-null   object
 7   환승노선번호   236 non-null    object
 8   환승노선명    275 non-null    object
 9   역위도      1015 non-null   float64
 10  역경도      1015 non-null   float64
 11  운영기관명    1015 non-null   object
 12  역사도로명주소  1015 non-null   object
 13  역사전화번호   1015 non-null   object
 14  데이터기준일자  1015 non-null   object
 15  제공기관코드   1015 non-null   object
 16  제공기관명    1015 non-null   object
dtypes: float64(2), object(15)
memory usage: 134.9+ KB

In [35]:
len(sub)

1015

In [36]:
seoul_sub = sub[sub['역사도로명주소'].str.contains('서울특별시')]
seoul_sub

,역번호,역사명,노선번호,노선명,영문역사명,한자역사명,환승역구분,환승노선번호,환승노선명,역위도,역경도,운영기관명,역사도로명주소,역사전화번호,데이터기준일자,제공기관코드,제공기관명
0,2545,군자,S1105,서울 도시철도 5호선,Gunja,君子,환승역,S1107,서울 도시철도 7호선,37.557134,127.079433,서울교통공사,서울특별시 광진구 천호대로 지하550,02-6311-5441,2021-04-09,B553766,서울교통공사
1,2546,아차산,S1105,서울 도시철도 5호선,Achasan,峨嵯山,일반역,NaN,NaN,37.552036,127.089601,서울교통공사,서울특별시 광진구 천호대로 지하657,02-6311-5451,2021-04-09,B553766,서울교통공사
2,2547,광나루,S1105,서울 도시철도 5호선,Gwangnaru,廣渡口,일반역,NaN,NaN,37.545048,127.103512,서울교통공사,서울특별시 광진구 아차산로 지하571 (광장동),02-6311-5461,2021-04-09,B553766,서울교통공사
3,2548,천호,S1105,서울 도시철도 5호선,Cheonho,千戶,일반역,NaN,NaN,37.538424,127.123623,서울교통공사,서울특별시 강동구 천호대로 지하997 (천호동),02-6311-5471,2021-04-09,B553766,서울교통공사
4,2549,강동,S1105,서울 도시철도 5호선,Gangdong,江東,일반역,NaN,NaN,37.535879,127.132079,서울교통공사,서울특별시 강동구 천호대로 지하1097 (천호동),02-6311-5481,2021-04-09,B553766,서울교통공사
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
910,4135,한성백제,S1109,서울 도시철도 9호선,Hanseong Baekje,漢城百?,일반역,NaN,NaN,37.516865,127.118185,서울교통공사,서울특별시 송파구 위례성대로 51,02-2656-0935,2021-04-09,B553766,서울교통공사
911,4136,올림픽공원,S1109,서울 도시철도 9호선,Olympic Park,올림픽公園(韓國體大),환승역,S1105,서울 도시철도 5호선,37.516088,127.130600,서울교통공사,서울특별시 송파구 양재대로 1233,02-2656-0936,2021-04-09,B553766,서울교통공사
912,4137,둔촌오륜,S1109,서울 도시철도 9호선,Dunchon Oryun,遁村五輪,일반역,NaN,NaN,37.517975,127.140170,서울교통공사,서울특별시 송파구 강동대로 327,02-2656-0937,2021-04-09,B553766,서울교통공사
913,4138,중앙보훈병원,S1109,서울 도시철도 9호선,VHS Medical Center,中央報?病院,일반역,NaN,NaN,37.529614,127.142757,서울교통공사,서울특별시 강동구 명일로 117,02-2656-0938,2021-04-09,B553766,서울교통공사
923,109,김포공항역,L4101,김포골드라인,Gimpo Airport,金浦空港,환승역,NaN,"공항철도,서울교통공사5호선,서울교통공사9호선운영㈜",37.562335,126.801951,김포골드라인운영㈜,서울특별시 강서구 하늘길77,031-8048-1790,2021-04-15,4090000,경기도 김포시

In [37]:
seoul_sub.to_excel('전국도시철도역사정보표준데이터_서울.xlsx', index=False)

In [39]:
nowon_sub = seoul_sub[seoul_sub['역사도로명주소'].str.contains('노원구')]
nowon_sub.shape

(13, 17)

In [41]:
nowon_sub.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13 entries, 51 to 842
Data columns (total 17 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   역번호      13 non-null     object
 1   역사명      13 non-null     object
 2   노선번호     13 non-null     object
 3   노선명      13 non-null     object
 4   영문역사명    13 non-null     object
 5   한자역사명    13 non-null     object
 6   환승역구분    13 non-null     object
 7   환승노선번호   5 non-null      object
 8   환승노선명    5 non-null      object
 9   역위도      13 non-null     float64
 10  역경도      13 non-null     float64
 11  운영기관명    13 non-null     object
 12  역사도로명주소  13 non-null     object
 13  역사전화번호   13 non-null     object
 14  데이터기준일자  13 non-null     object
 15  제공기관코드   13 non-null     object
 16  제공기관명    13 non-null     object
dtypes: float64(2), object(15)
memory usage: 1.8+ KB

In [43]:
nowon_sub.head(3)

,역번호,역사명,노선번호,노선명,영문역사명,한자역사명,환승역구분,환승노선번호,환승노선명,역위도,역경도,운영기관명,역사도로명주소,역사전화번호,데이터기준일자,제공기관코드,제공기관명
51,2645,석계,S1106,서울 도시철도 6호선,Seokgye,石溪,환승역,S1101,서울 도시철도 1호선,37.614983,127.065561,서울교통공사,서울특별시 노원구 화랑로 지하347-1 (월계동),02-6311-6441,2021-04-09,B553766,서울교통공사
52,2646,태릉입구,S1106,서울 도시철도 6호선,Taereung,泰陵,환승역,S1107,서울 도시철도 7호선,37.617965,127.074894,서울교통공사,서울특별시 노원구 동일로 지하992-1 (공릉동),02-6311-7171,2021-04-09,B553766,서울교통공사
53,2647,화랑대,S1106,서울 도시철도 6호선,Hwarangdae,花郞臺,일반역,NaN,NaN,37.620131,127.084426,서울교통공사,서울특별시 노원구 화랑로 지하510,02-6311-6461,2021-04-09,B553766,서울교통공사

In [47]:
nowon_sub1 = nowon_sub.drop(['영문역사명', '한자역사명', '환승노선번호', '환승노선명', '운영기관명', '역사전화번호', '데이터기준일자', '제공기관코드', '제공기관명'], axis=1)
nowon_sub1

,역번호,역사명,노선번호,노선명,환승역구분,역위도,역경도,역사도로명주소
51,2645,석계,S1106,서울 도시철도 6호선,환승역,37.614983,127.065561,서울특별시 노원구 화랑로 지하347-1 (월계동)
52,2646,태릉입구,S1106,서울 도시철도 6호선,환승역,37.617965,127.074894,서울특별시 노원구 동일로 지하992-1 (공릉동)
53,2647,화랑대,S1106,서울 도시철도 6호선,일반역,37.620131,127.084426,서울특별시 노원구 화랑로 지하510
58,2713,수락산,S1107,서울 도시철도 7호선,일반역,37.677916,127.055234,서울특별시 노원구 동일로 지하1662 (상계동)
59,2714,마들,S1107,서울 도시철도 7호선,일반역,37.665162,127.057334,서울특별시 노원구 동일로 지하1530-1 (상계동)
60,2715,노원,S1107,서울 도시철도 7호선,환승역,37.654960,127.062005,서울특별시 노원구 상계로 69-1 (상계동)
198,409,당고개,S1104,서울 도시철도 4호선,일반역,37.670326,127.078955,서울특별시 노원구 상계로 305 (상계동)
199,410,상계,S1104,서울 도시철도 4호선,일반역,37.660905,127.073129,서울특별시 노원구 상계로 182 (상계동)
200,411,노원,S1104,서울 도시철도 4호선,환승역,37.655149,127.062495,서울특별시 노원구 상계로 69-1 (상계동)
838,2716,중계,S1107,서울 도시철도 7호선,일반역,37.645217,127.064083,서울특별시 노원구 동일로 지하1308-1 (중계동)
839,2717,하계,S1107,서울 도시철도 7호선,일반역,37.636427,127.067815,서울특별시 노원구 동일로 지하1196(하계동)
840,2718,공릉,S1107,서울 도시철도 7호선,일반역,37.625513,127.072824,서울특별시 노원구 동일로 지하1074
842,2719,태릉입구,S1107,서울 도시철도 7호선,환승역,37.618165,127.074694,서울특별시 노원구 동일로 지하992-1 (공릉동)

In [48]:
nowon_sub1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13 entries, 51 to 842
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   역번호      13 non-null     object
 1   역사명      13 non-null     object
 2   노선번호     13 non-null     object
 3   노선명      13 non-null     object
 4   환승역구분    13 non-null     object
 5   역위도      13 non-null     float64
 6   역경도      13 non-null     float64
 7   역사도로명주소  13 non-null     object
dtypes: float64(2), object(6)
memory usage: 936.0+ bytes

In [51]:
nowon_sub1['호선'] = nowon_sub1['노선번호'].str[4:]
nowon_sub1

,역번호,역사명,노선번호,노선명,환승역구분,역위도,역경도,역사도로명주소,호선
51,2645,석계,S1106,서울 도시철도 6호선,환승역,37.614983,127.065561,서울특별시 노원구 화랑로 지하347-1 (월계동),6
52,2646,태릉입구,S1106,서울 도시철도 6호선,환승역,37.617965,127.074894,서울특별시 노원구 동일로 지하992-1 (공릉동),6
53,2647,화랑대,S1106,서울 도시철도 6호선,일반역,37.620131,127.084426,서울특별시 노원구 화랑로 지하510,6
58,2713,수락산,S1107,서울 도시철도 7호선,일반역,37.677916,127.055234,서울특별시 노원구 동일로 지하1662 (상계동),7
59,2714,마들,S1107,서울 도시철도 7호선,일반역,37.665162,127.057334,서울특별시 노원구 동일로 지하1530-1 (상계동),7
60,2715,노원,S1107,서울 도시철도 7호선,환승역,37.654960,127.062005,서울특별시 노원구 상계로 69-1 (상계동),7
198,409,당고개,S1104,서울 도시철도 4호선,일반역,37.670326,127.078955,서울특별시 노원구 상계로 305 (상계동),4
199,410,상계,S1104,서울 도시철도 4호선,일반역,37.660905,127.073129,서울특별시 노원구 상계로 182 (상계동),4
200,411,노원,S1104,서울 도시철도 4호선,환승역,37.655149,127.062495,서울특별시 노원구 상계로 69-1 (상계동),4
838,2716,중계,S1107,서울 도시철도 7호선,일반역,37.645217,127.064083,서울특별시 노원구 동일로 지하1308-1 (중계동),7
839,2717,하계,S1107,서울 도시철도 7호선,일반역,37.636427,127.067815,서울특별시 노원구 동일로 지하1196(하계동),7
840,2718,공릉,S1107,서울 도시철도 7호선,일반역,37.625513,127.072824,서울특별시 노원구 동일로 지하1074,7
842,2719,태릉입구,S1107,서울 도시철도 7호선,환승역,37.618165,127.074694,서울특별시 노원구 동일로 지하992-1 (공릉동),7

In [52]:
nowon_sub1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13 entries, 51 to 842
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   역번호      13 non-null     object
 1   역사명      13 non-null     object
 2   노선번호     13 non-null     object
 3   노선명      13 non-null     object
 4   환승역구분    13 non-null     object
 5   역위도      13 non-null     float64
 6   역경도      13 non-null     float64
 7   역사도로명주소  13 non-null     object
 8   호선       13 non-null     object
dtypes: float64(2), object(7)
memory usage: 1.0+ KB

In [53]:
nowon_sub1.to_excel('노원구_지하철.xlsx', index=False)