In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns

import statsmodels.api as sm
import statsmodels.formula.api as smf

In [2]:
import math

In [9]:
data_m = pd.read_csv('C:/Users/1102j/anaconda/dataScience/project/apt_data_month_added.csv', thousands=',', encoding='utf-8')
data_m

,시군구,번지,본번,부번,단지명,전월세구분,전용면적(㎡),계약년월,계약일,전월세(만원),...,공원,대형마트,백화점,cctv,주차대수,브랜드,주차관제,승강기,복도유형,난방방식
0,서울특별시 노원구 공릉동,683-30,683,30,(683-30),월세,20.00,202001,6,20500,...,0.821341,1.49,4.33,37.0,219.0,0,NaN,NaN,NaN,NaN
1,서울특별시 노원구 공릉동,683-30,683,30,(683-30),월세,20.00,202007,9,20500,...,0.821341,1.49,4.33,37.0,219.0,0,NaN,NaN,NaN,NaN
2,서울특별시 노원구 공릉동,683-30,683,30,(683-30),월세,20.00,202008,6,20500,...,0.821341,1.49,4.33,37.0,219.0,0,NaN,NaN,NaN,NaN
3,서울특별시 노원구 공릉동,683-30,683,30,(683-30),월세,20.00,202008,21,16000,...,0.821341,1.49,4.33,37.0,219.0,0,NaN,NaN,NaN,NaN
4,서울특별시 노원구 공릉동,683-30,683,30,(683-30),월세,20.00,202009,7,20000,...,0.821341,1.49,4.33,37.0,219.0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3997,서울특별시 노원구 하계동,270,270,0,현대,월세,72.20,202009,10,31000,...,0.267815,0.46,2.11,167.0,1386.0,0,0.0,44.0,0.0,2.0
3998,서울특별시 노원구 하계동,270,270,0,현대,월세,72.20,202009,10,31000,...,0.267815,0.46,2.11,167.0,1386.0,0,0.0,44.0,0.0,2.0
3999,서울특별시 노원구 하계동,270,270,0,현대,월세,84.95,202010,10,41400,...,0.267815,0.46,2.11,167.0,1386.0,0,0.0,44.0,0.0,2.0
4000,서울특별시 노원구 하계동,270,270,0,현대,월세,84.95,202011,23,39500,...,0.267815,0.46,2.11,167.0,1386.0,0,0.0,44.0,0.0,2.0
4001,서울특별시 노원구 하계동,270,270,0,현대,월세,84.95,202012,23,38500,...,0.267815,0.46,2.11,167.0,1386.0,0,0.0,44.0,0.0,2.0

In [10]:
data_y = pd.read_csv('C:/Users/1102j/anaconda/dataScience/project/apt_data_year(3법추가본).csv', thousands=',', encoding='utf-8')
data_y

,시군구,번지,본번,부번,단지명,전월세구분,전용면적(㎡),계약년월,계약일,전월세(만원),...,대형마트,백화점,cctv,주차대수,브랜드,복도유형,난방방식,승강기,주차관제,3법
0,서울특별시 노원구 공릉동,404-3,404,3,건영아파트,전세,84.75,202007,18,34000,...,0.88,3.54,37.0,219.0,0,NaN,NaN,NaN,NaN,NaN
1,서울특별시 노원구 공릉동,744,744,0,건영장미아파트,전세,84.88,202002,8,35000,...,1.24,3.18,37.0,219.0,0,0.0,0.0,5.0,0.0,0.0
2,서울특별시 노원구 공릉동,744,744,0,건영장미아파트,전세,84.88,202007,1,40000,...,1.24,3.18,37.0,219.0,0,0.0,0.0,5.0,0.0,0.0
3,서울특별시 노원구 공릉동,744,744,0,건영장미아파트,전세,59.87,202007,11,27000,...,1.24,3.18,37.0,219.0,0,0.0,0.0,5.0,0.0,0.0
4,서울특별시 노원구 공릉동,744,744,0,건영장미아파트,전세,59.87,202007,13,28000,...,1.24,3.18,37.0,219.0,0,0.0,0.0,5.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10533,서울특별시 노원구 하계동,270,270,0,현대,전세,84.95,202010,29,60000,...,0.46,2.11,167.0,1386.0,0,0.0,2.0,44.0,0.0,1.0
10534,서울특별시 노원구 하계동,270,270,0,현대,전세,84.95,202011,7,42000,...,0.46,2.11,167.0,1386.0,0,0.0,2.0,44.0,0.0,1.0
10535,서울특별시 노원구 하계동,270,270,0,현대,전세,84.95,202012,2,65000,...,0.46,2.11,167.0,1386.0,0,0.0,2.0,44.0,0.0,1.0
10536,서울특별시 노원구 하계동,270,270,0,현대,전세,84.95,202012,9,37800,...,0.46,2.11,167.0,1386.0,0,0.0,2.0,44.0,0.0,1.0
10537,서울특별시 노원구 하계동,270,270,0,현대,전세,71.68,202012,22,45000,...,0.46,2.11,167.0,1386.0,0,0.0,2.0,44.0,0.0,1.0

# 월세

In [11]:
data_m = data_m.dropna()

In [12]:
xm = data_m[['전용면적(㎡)', '층', '건축년도', '초등학교', '병원', '공원', '대형마트', '백화점', 'cctv', '주차대수', '브랜드', '주차관제', '승강기', '복도유형', '난방방식']]
ym = data_m[['전월세(만원)']]

In [46]:
ym['전월세(만원)'] = np.log(ym)

<ipython-input-46-9c8715ba90b9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ym['전월세(만원)'] = np.log(ym)

In [13]:
model = sm.OLS(ym, xm)
result = model.fit()

In [14]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                전월세(만원)   R-squared (uncentered):                   0.955
Model:                            OLS   Adj. R-squared (uncentered):              0.955
Method:                 Least Squares   F-statistic:                              4828.
Date:                Sun, 06 Jun 2021   Prob (F-statistic):                        0.00
Time:                        17:23:49   Log-Likelihood:                         -34534.
No. Observations:                3448   AIC:                                  6.910e+04
Df Residuals:                    3433   BIC:                                  6.919e+04
Df Model:                          15
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
전용면적(㎡)      507.0936      5.737     88.394      0.000     495.846     518.341
층            114.3084     20.192      5.661      0.000      74.719     153.898
건축년도          -1.0049      0.282     -3.565      0.000      -1.557      -0.452
초등학교        -956.2518    807.316     -1.184      0.236   -2539.121     626.617
병원          -493.3536    157.245     -3.137      0.002    -801.656    -185.051
공원         -2187.0228    531.060     -4.118      0.000   -3228.248   -1145.798
대형마트       -2020.1939    229.845     -8.789      0.000   -2470.840   -1569.548
백화점          122.7261    104.319      1.176      0.239     -81.808     327.260
cctv          -9.3284      2.369     -3.938      0.000     -13.972      -4.684
주차대수           1.0456      0.290      3.607      0.000       0.477       1.614
브랜드         8592.4245    780.379     11.011      0.000    7062.369    1.01e+04
주차관제       -1183.6197    391.647     -3.022      0.003   -1951.504    -415.736
승강기            5.5954     14.565      0.384      0.701     -22.961      34.152
복도유형       -2683.3188    231.160    -11.608      0.000   -3136.543   -2230.094
난방방식        1230.2603    200.869      6.125      0.000     836.425    1624.096
==============================================================================
Omnibus:                      601.836   Durbin-Watson:                   1.175
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            11031.665
Skew:                           0.257   Prob(JB):                         0.00
Kurtosis:                      11.748   Cond. No.                     2.06e+04
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 2.06e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# 월세 (조정)

In [24]:
# P값이 높은 행 삭제
xm = data_m[['전용면적(㎡)', '층', '건축년도', '병원', '공원', '대형마트', 'cctv', '주차대수', '브랜드', '복도유형', '난방방식']]
ym = data_m[['전월세(만원)']]

In [20]:
ym['전월세(만원)'] = np.log(ym)

<ipython-input-20-9c8715ba90b9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ym['전월세(만원)'] = np.log(ym)

In [25]:
xm['공원'] = xm['공원'] ** 2
xm['전용면적(㎡)'] = xm['전용면적(㎡)'] ** 2
xm['층'] = xm['층'] ** 2
xm['건축년도'] = xm['건축년도'] ** 2

<ipython-input-25-607a29d3bfe8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xm['공원'] = xm['공원'] ** 2
<ipython-input-25-607a29d3bfe8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xm['전용면적(㎡)'] = xm['전용면적(㎡)'] ** 2
<ipython-input-25-607a29d3bfe8>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xm['층'] = xm['층'] ** 2
<ipython-input-25-607a29d3bfe8>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xm['건축년도'] = xm['건축년도'] ** 2

In [26]:
model_m = sm.OLS(ym, xm)
result_m = model_m.fit()

In [27]:
result_m.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                전월세(만원)   R-squared (uncentered):                   0.949
Model:                            OLS   Adj. R-squared (uncentered):              0.949
Method:                 Least Squares   F-statistic:                              5870.
Date:                Sun, 06 Jun 2021   Prob (F-statistic):                        0.00
Time:                        17:24:15   Log-Likelihood:                         -34725.
No. Observations:                3448   AIC:                                  6.947e+04
Df Residuals:                    3437   BIC:                                  6.954e+04
Df Model:                          11
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
전용면적(㎡)        3.5593      0.043     83.262      0.000       3.475       3.643
층              6.2731      1.123      5.588      0.000       4.072       8.474
건축년도           0.0033      0.000     31.809      0.000       0.003       0.003
병원          -478.0486    163.453     -2.925      0.003    -798.524    -157.573
공원         -1832.2943    507.201     -3.613      0.000   -2826.740    -837.849
대형마트       -1859.8522    233.336     -7.971      0.000   -2317.343   -1402.362
cctv          -6.3013      2.403     -2.623      0.009     -11.012      -1.591
주차대수           1.1360      0.238      4.779      0.000       0.670       1.602
브랜드         8038.6034    813.685      9.879      0.000    6443.247    9633.959
복도유형       -2545.0886    241.346    -10.545      0.000   -3018.285   -2071.892
난방방식        1425.4677    199.067      7.161      0.000    1035.166    1815.770
==============================================================================
Omnibus:                      557.860   Durbin-Watson:                   1.208
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            10518.140
Skew:                          -0.027   Prob(JB):                         0.00
Kurtosis:                      11.556   Cond. No.                     3.32e+07
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 3.32e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# 전세

In [28]:
data_y = data_y.dropna()

In [29]:
xy = data_y[['전용면적(㎡)', '층', '건축년도', '초등학교', '병원', '공원', '대형마트', '백화점', 'cctv', '주차대수', '브랜드', '주차관제', '승강기', '복도유형', '난방방식', '3법']]
yy = data_y[['전월세(만원)']]

In [106]:
yy['전월세(만원)'] = np.log(yy)
yy

<ipython-input-106-16a4bfcd1bb0>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yy['전월세(만원)'] = np.log(yy)

         전월세(만원)
1      10.463103
2      10.596635
3      10.203592
4      10.239960
5      10.596635
...          ...
10533  11.002100
10534  10.645425
10535  11.082143
10536  10.540064
10537  10.714418

[9490 rows x 1 columns]

In [30]:
model_y = sm.OLS(yy, xy)
result_y = model_y.fit()

In [31]:
result_y.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                전월세(만원)   R-squared (uncentered):                   0.951
Model:                            OLS   Adj. R-squared (uncentered):              0.951
Method:                 Least Squares   F-statistic:                          1.160e+04
Date:                Sun, 06 Jun 2021   Prob (F-statistic):                        0.00
Time:                        17:24:23   Log-Likelihood:                         -96813.
No. Observations:                9490   AIC:                                  1.937e+05
Df Residuals:                    9474   BIC:                                  1.938e+05
Df Model:                          16
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
전용면적(㎡)      494.3434      3.582    138.018      0.000     487.322     501.364
층            113.2306     14.108      8.026      0.000      85.577     140.884
건축년도          -1.6243      0.212     -7.656      0.000      -2.040      -1.208
초등학교        -191.9154    536.859     -0.357      0.721   -1244.274     860.443
병원          -778.0673    109.200     -7.125      0.000    -992.122    -564.012
공원         -1899.3237    392.333     -4.841      0.000   -2668.380   -1130.268
대형마트       -1912.0486    155.594    -12.289      0.000   -2217.047   -1607.050
백화점          485.0397     71.142      6.818      0.000     345.587     624.493
cctv           0.2712      1.701      0.159      0.873      -3.064       3.606
주차대수           0.8005      0.214      3.744      0.000       0.381       1.220
브랜드         8538.4619    483.005     17.678      0.000    7591.668    9485.255
주차관제        -196.6189    286.798     -0.686      0.493    -758.805     365.567
승강기          -22.4086     10.899     -2.056      0.040     -43.773      -1.045
복도유형       -3436.6827    173.261    -19.835      0.000   -3776.312   -3097.053
난방방식         823.9882    138.577      5.946      0.000     552.347    1095.629
3법          3714.4924    139.123     26.699      0.000    3441.782    3987.203
==============================================================================
Omnibus:                     1735.757   Durbin-Watson:                   1.053
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            20038.510
Skew:                           0.534   Prob(JB):                         0.00
Kurtosis:                      10.038   Cond. No.                     1.89e+04
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 1.89e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# 전세 (조정)

In [32]:
# P값 높은 행 삭제
xy = data_y[['전용면적(㎡)', '층', '건축년도', '병원', '공원', '대형마트', '백화점', '주차대수', '브랜드', '복도유형', '난방방식']]
yy = data_y[['전월세(만원)']]

In [33]:
yy['전월세(만원)'] = np.log(yy)

<ipython-input-33-2e1966bb2513>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yy['전월세(만원)'] = np.log(yy)

In [230]:
xy['공원'] = xy['공원'] ** 2
xy['전용면적(㎡)'] = xy['전용면적(㎡)'] ** 2
xy['층'] = xy['층'] ** 2
xy['건축년도'] = xy['건축년도'] ** 2
xy['층'] = xy['층'] ** 2

<ipython-input-230-0315feb7abc5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xy['공원'] = xy['공원'] ** 2
<ipython-input-230-0315feb7abc5>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xy['전용면적(㎡)'] = xy['전용면적(㎡)'] ** 2
<ipython-input-230-0315feb7abc5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xy['층'] = xy['층'] ** 2
<ipython-input-230-0315feb7abc5>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xy['건축년도'] = xy['건축년도'] ** 2
<ipython-input-230-0315feb7abc5>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xy['층'] = xy['층'] ** 2

In [34]:
model_y = sm.OLS(yy, xy)
result_y = model_y.fit()

In [35]:
result_y.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                전월세(만원)   R-squared (uncentered):                   0.999
Model:                            OLS   Adj. R-squared (uncentered):              0.999
Method:                 Least Squares   F-statistic:                          1.395e+06
Date:                Sun, 06 Jun 2021   Prob (F-statistic):                        0.00
Time:                        17:24:28   Log-Likelihood:                         -330.40
No. Observations:                9490   AIC:                                      682.8
Df Residuals:                    9479   BIC:                                      761.5
Df Model:                          11
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
전용면적(㎡)        0.0167      0.000    122.128      0.000       0.016       0.017
층              0.0037      0.001      6.903      0.000       0.003       0.005
건축년도           0.0046   7.14e-06    639.804      0.000       0.005       0.005
병원            -0.0498      0.004    -11.973      0.000      -0.058      -0.042
공원            -0.0097      0.015     -0.652      0.515      -0.039       0.019
대형마트          -0.0365      0.006     -6.253      0.000      -0.048      -0.025
백화점            0.0120      0.003      4.480      0.000       0.007       0.017
주차대수         2.76e-05   3.68e-06      7.504      0.000    2.04e-05    3.48e-05
브랜드            0.1870      0.017     10.698      0.000       0.153       0.221
복도유형          -0.0814      0.006    -13.443      0.000      -0.093      -0.070
난방방식          -0.0017      0.005     -0.334      0.739      -0.011       0.008
==============================================================================
Omnibus:                     4656.372   Durbin-Watson:                   1.262
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            96044.603
Skew:                          -1.876   Prob(JB):                         0.00
Kurtosis:                      18.127   Cond. No.                     1.55e+04
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 1.55e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# 월세(데이터추가)

In [36]:
data_m = pd.read_csv('C:/Users/1102j/anaconda/dataScience/project/month_nowon.csv', thousands=',', encoding='euckr')
data_m

,시군구,번지,본번,부번,단지명,전월세구분,전용면적(㎡),계약년월,계약일,전월세(만원),...,주차대수,브랜드,주차관제,승강기,복도유형,난방방식,단지명(K-apt),일반관리,경비관리,청소관리
0,서울특별시 노원구 공릉동,683-30,683,30,(683-30),월세,20.00,202001,6,20500,...,219.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,서울특별시 노원구 공릉동,683-30,683,30,(683-30),월세,20.00,202007,9,20500,...,219.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,서울특별시 노원구 공릉동,683-30,683,30,(683-30),월세,20.00,202008,6,20500,...,219.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,서울특별시 노원구 공릉동,683-30,683,30,(683-30),월세,20.00,202008,21,16000,...,219.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,서울특별시 노원구 공릉동,683-30,683,30,(683-30),월세,20.00,202009,7,20000,...,219.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3997,서울특별시 노원구 하계동,270,270,0,현대,월세,72.20,202009,10,31000,...,1386.0,0,0.0,44.0,0.0,중앙난방,하계현대우성,17.0,24.0,13.0
3998,서울특별시 노원구 하계동,270,270,0,현대,월세,72.20,202009,10,31000,...,1386.0,0,0.0,44.0,0.0,중앙난방,하계현대우성,17.0,24.0,13.0
3999,서울특별시 노원구 하계동,270,270,0,현대,월세,84.95,202010,10,41400,...,1386.0,0,0.0,44.0,0.0,중앙난방,하계현대우성,17.0,24.0,13.0
4000,서울특별시 노원구 하계동,270,270,0,현대,월세,84.95,202011,23,39500,...,1386.0,0,0.0,44.0,0.0,중앙난방,하계현대우성,17.0,24.0,13.0
4001,서울특별시 노원구 하계동,270,270,0,현대,월세,84.95,202012,23,38500,...,1386.0,0,0.0,44.0,0.0,중앙난방,하계현대우성,17.0,24.0,13.0

In [67]:
data_m.난방방식 = data_m.난방방식.replace('개별난방', 1)
data_m.난방방식 = data_m.난방방식.replace('지역난방', 0)
data_m.난방방식 = data_m.난방방식.replace('중앙난방', 0)

In [68]:
data_m.to_csv('노원월세.csv', index=False, encoding='euckr')

In [76]:
data_m = pd.read_csv('C:/Users/1102j/anaconda/dataScience/project/노원월세.csv', thousands=',', encoding='euckr')
data_m

,시군구,번지,본번,부번,단지명,전월세구분,전용면적(㎡),계약년월,계약일,전월세(만원),...,주차대수,브랜드,주차관제,승강기,복도유형,난방방식,단지명(K-apt),일반관리,경비관리,청소관리
0,서울특별시 노원구 공릉동,683-30,683,30,(683-30),월세,20.00,202001,6,20500,...,219.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,서울특별시 노원구 공릉동,683-30,683,30,(683-30),월세,20.00,202007,9,20500,...,219.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,서울특별시 노원구 공릉동,683-30,683,30,(683-30),월세,20.00,202008,6,20500,...,219.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,서울특별시 노원구 공릉동,683-30,683,30,(683-30),월세,20.00,202008,21,16000,...,219.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,서울특별시 노원구 공릉동,683-30,683,30,(683-30),월세,20.00,202009,7,20000,...,219.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3997,서울특별시 노원구 하계동,270,270,0,현대,월세,72.20,202009,10,31000,...,1386.0,0,0.0,44.0,0.0,0.0,하계현대우성,17.0,24.0,13.0
3998,서울특별시 노원구 하계동,270,270,0,현대,월세,72.20,202009,10,31000,...,1386.0,0,0.0,44.0,0.0,0.0,하계현대우성,17.0,24.0,13.0
3999,서울특별시 노원구 하계동,270,270,0,현대,월세,84.95,202010,10,41400,...,1386.0,0,0.0,44.0,0.0,0.0,하계현대우성,17.0,24.0,13.0
4000,서울특별시 노원구 하계동,270,270,0,현대,월세,84.95,202011,23,39500,...,1386.0,0,0.0,44.0,0.0,0.0,하계현대우성,17.0,24.0,13.0
4001,서울특별시 노원구 하계동,270,270,0,현대,월세,84.95,202012,23,38500,...,1386.0,0,0.0,44.0,0.0,0.0,하계현대우성,17.0,24.0,13.0

In [77]:
data_m = data_m.dropna()

In [78]:
xm = data_m[['전용면적(㎡)', '건축년도', '병원', '공원', '대형마트', '백화점 ', 'cctv', '브랜드', '주차관제', '승강기', '복도유형', '일반관리', '경비관리']]
ym = data_m[['전월세(만원)']]

In [79]:
ym['전월세(만원)'] = np.log(ym)

<ipython-input-79-9c8715ba90b9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ym['전월세(만원)'] = np.log(ym)

In [80]:
model_x = sm.OLS(ym, xm)
result_x = model_x.fit()

In [81]:
result_x.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                전월세(만원)   R-squared (uncentered):                   0.999
Model:                            OLS   Adj. R-squared (uncentered):              0.999
Method:                 Least Squares   F-statistic:                          3.740e+05
Date:                Sun, 06 Jun 2021   Prob (F-statistic):                        0.00
Time:                        17:40:27   Log-Likelihood:                         -213.78
No. Observations:                3287   AIC:                                      453.6
Df Residuals:                    3274   BIC:                                      532.8
Df Model:                          13
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
전용면적(㎡)        0.0190      0.000     67.089      0.000       0.018       0.020
건축년도           0.0045   1.28e-05    353.970      0.000       0.005       0.005
병원            -0.0298      0.008     -3.832      0.000      -0.045      -0.015
공원            -0.1423      0.026     -5.484      0.000      -0.193      -0.091
대형마트          -0.1004      0.011     -8.822      0.000      -0.123      -0.078
백화점            0.0247      0.006      4.194      0.000       0.013       0.036
cctv          -0.0004      0.000     -3.259      0.001      -0.001      -0.000
브랜드            0.1843      0.037      4.974      0.000       0.112       0.257
주차관제          -0.1474      0.018     -7.978      0.000      -0.184      -0.111
승강기            0.0044      0.001      6.063      0.000       0.003       0.006
복도유형          -0.0497      0.011     -4.520      0.000      -0.071      -0.028
일반관리          -0.0061      0.002     -3.768      0.000      -0.009      -0.003
경비관리           0.0033      0.001      4.979      0.000       0.002       0.005
==============================================================================
Omnibus:                     1703.845   Durbin-Watson:                   1.126
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            16675.068
Skew:                          -2.263   Prob(JB):                         0.00
Kurtosis:                      13.063   Cond. No.                     1.65e+04
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 1.65e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""